### ISSUE TITLE
presentPopupBarWithContentViewController with hidesBottomBarWhenPushed

### ISSUE THREAD

**Issue by atulvuliv** [LeoNatan/LNPopupController#101]
Hi,

I am trying to present PopUpBar on a UITabBarController whose tab bar is hidden using hidesBottomBarWhenPushed by one of the view controllers while pushing in navigation heirarchy. 

It results in a floating PopUpBar over the tab bar which is hidden. Is there any workaround for this? Or am I doing it the wrong way?

Adding a screenshot for reference:

![music_player](https://cloud.githubusercontent.com/assets/16804660/18313498/a999fe2a-752c-11e6-90e2-3f00135caf9c.jpg)

Thanks

**Comment by LeoNatan** [comment]
As explicitly stated in the readme, this is not supported.

**Opening the popup while it is hidden due to hidesBottomBarWhenPushed is not supported and may produce undefined behavior.**

**Comment by MaxHasADHD** [comment]
@LeoNatan Any reason for this? Is there no way to check if it is hidden or net yet?
@atulvuliv What did you do to fix this? 

A user action from the pushed view should present it, but not in the view.

**Comment by LeoNatan** [comment]
When the bottom bar is hidden, there are issues with how to layout the popup bar. This is explicitly not supported because there are issues.

**Comment by LeoNatan** [comment]
To fix, do not present a popup bar on a navigation controller or a tab bar controller with a hidden bottom bar. It's that simple. If your current controller hides the bottom bar, present it on your current controller directly.

**Comment by MaxHasADHD** [comment]
@LeoNatan it wouldn't make sense to display a popup for a controller that I'm already in. The solution I came up with is detecting if the root view is being viewed or not, then present it, and check in `viewWillAppear` if I need to display it. The issue with this is I have to copy that same code now into every possible view in the tab bar because it can show up in any of the tabs, and dismisses when hiding the tab bar after a push, but shouldn't show in the middle of the view with no tab bar.

**Comment by saltwat5r** [comment]
For me sample solution is setting `extendedLayoutIncludesOpaqueBars = true` in controller which shows the Popup Controller.
