### ISSUE TITLE
Support custom controls in Popup Bar

### ISSUE THREAD

**Issue by chauhan130** [LeoNatan/LNPopupController#106]
I really like this controloller and it will be even great if you allow to add custom controls in popup bar itself.

**Comment by LeoNatan** [comment]
This has come up several times. The problem right now is, the framework makes assumptions about the view hierarchy it expects, and that hierarchy is updated using the popup item. The idea was to have a similar developer experience as `UINavigationBar` and `UINavigationItem`. I am not sure how to open this to developers properly, with all the assumptions the framework makes, but API-wise as well as internally. I will leave this open because several people have asked for this. Pull requests are welcome.

**Comment by mmoloksher** [comment]
I second this feature request... It would be awesome to pass down a custom view controller acting as pop up bar

**Comment by LeoNatan** [comment]
It is out of scope for the 2.0 milestone, but will think about it for a future milestone.

**Comment by yarodevuci** [comment]
Why API is locked ?

**Comment by LeoNatan** [comment]
What do you mean "locked"?

**Comment by yarodevuci** [comment]
I mean that I only see the headers of the library but I don't see how you implementing everything

**Comment by LeoNatan** [comment]
The project is open source. Please do not hijack this issue. If you have problems, please open a new issue.

**Comment by LeoNatan** [comment]
Implemented, but I will not have time to update the documentation right now.
Please see example project for a full example. Please open issues if you find missing features or have enhancement requests.

CC @chauhan130 @mmoloksher

**Comment by singhamit089** [comment]
@LeoNatan Awesome! exactly what I was looking for 🍻

**Comment by LeoNatan** [comment]
@singhamit089 Great! Let me know if you hit any speed bumps.

**Comment by singhamit089** [comment]
Hey @LeoNatan is this not available with cocoapods yet ?

**Comment by LeoNatan** [comment]
No. As stated in the readme, it is only available through Carthage.
