### ISSUE TITLE
Popup bar does not appear when presented from UINavigationController with hidden toolbar

### ISSUE THREAD

**Issue by btc** [LeoNatan/LNPopupController#128]
In a basic example, the popupBar no longer appears on calls to presentPopupBar. However, the completion callback is still called.

I noticed it was broken when I updated to 5a6bd3038af53989f468609ce3670d10647e9cea.

However, it was working at 0e3111e78916d6f79474c3ccd2b2f7ff6bb33b72.

Here is an example project that reproduces the issue:

https://github.com/btc/LNPopupControllerBugExample

master is broken
"old" branch works

**Comment by btc** [comment]
updated:

breaks at 12118abf0f286c396c4b520c3e8cd6b5c085ae22
works at 2e54248f1a5c86044aa575b3f54e9b389468c30b

**Comment by LeoNatan** [comment]
These type of issues are not helping. Please provide properly worded explanation of what is not working.

**Comment by btc** [comment]
I apologize. I will elaborate.

**Comment by LeoNatan** [comment]
Please update your first comment with a proper description of the issue.

**Comment by btc** [comment]
Please see https://github.com/btc/LNPopupControllerBugExample

**Comment by LeoNatan** [comment]
I see the issue is related to hidden toolbar of the navigation controller. If the toolbar is visible, it works. Will investigate.

**Comment by btc** [comment]
I apologize for the poor communication the first time around. Thank you very much for creating this library.

**Comment by LeoNatan** [comment]
Are you sure the example project reproduces your issue in the same way as in your real app?

This is a known limitation (see README) and is very difficult to fix. **The scenario shown in the example project has never been supported or worked in the past.** In case you have a navigation controller with a hidden toolbar, you currently only have two options:

- Present on the inner view controller, rather than the navigation controller, but then when the popup opens, it will go under the navigation bar
- Add you navigation controller scene as a child controller or a view controller, and present the popup bar on that container controller.

I am not sure I have the time to fix this issue soon. I suggest going with solution #2.

**Comment by btc** [comment]
Interesting. Was it an accident that the popupBar appeared in 0e3111e?

**Comment by LeoNatan** [comment]
I tried running your example project with 2.0.0 as well as 1.4.6 and neither showed a popup bar.

**Comment by btc** [comment]
Did you tap the green button? The popupBar works on this branch ("old"):

https://github.com/btc/LNPopupControllerBugExample/tree/old

It's on commit 0e3111e78916d6f79474c3ccd2b2f7ff6bb33b72

**Comment by LeoNatan** [comment]
Solved 👍 
Please test on latest master.
