### ISSUE TITLE
Full Dynamic Content with out any images asset

### ISSUE THREAD

**Issue by farshadmb** [LeoNatan/LNPopupController#145]
#### Description

Hi Leo

At First you are so good and agree with some reason that you didn't use CocoaPods for your project. 
Second Why you don't try to make a full dynamic library without any dependency like images and any kind of resources??
Third We should override some methods to customize any view or content view you used in your library. why you didnt provide any customization style, CustomBarView. it's easy to use a customView property I think.

#### Steps to Reproduce

It's really good to change a list, I mention below
1 - Make a Customization Style 
2 - Make a CustomView Property

or if you have any documentation pls share us

**Comment by LeoNatan** [comment]
I don't understand what the problem is.
The library has images, and they are needed. They are part of the framework bundle. Follow the proper way to include in your project, [not CocoaPods](https://github.com/farshadmb/LNPopupController/commit/15c704e294ed47868c4c6d552c974dc31a618592), then it all works and images and resources are loaded. But you decided not to follow the readme. There is no problem here.
Second, there are many customization options. One of them is [`customBarViewController`](https://github.com/LeoNatan/LNPopupController/blob/master/LNPopupController/LNPopupController/LNPopupBar.h#L144), which allows exactly that, a custom view controller to control the view hierarchy of the popup bar. See the example project for an example.
