### ISSUE TITLE
iOS 8 Support Broken

### ISSUE THREAD

**Issue by farshadmb** [LeoNatan/LNPopupController#148]
iOS 8 doesn't support yet !!!
#### Description

- `*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[LNPopupCloseButton topAnchor]: unrecognized selector sent to instance 0x13926ae50'
` as mention to you topAnchor class support iOS 9 and later [apple documentation](https://developer.apple.com/reference/appkit/nslayoutanchor)

- bottomLayoutGuide doesn't support for any BarStyle or custom view 

- Cocoapods are support any kind of resource now and any dynamic library

#### Device, OS and Xcode Versions

iPhone 5S, iOS 8.4.1 Xcode 8.2.1

**Comment by LeoNatan** [comment]
Yes, I see the problem. I am not sure I want to support iOS 8. I might do a last version kind of thing, where I would introduce a fix, but then right away create a version that is iOS 9 and above, reverting the change. iOS 8 is very insignificant, and it's becoming a nuisance to support.

**Comment by farshadmb** [comment]
@LeoNatan Are you kidding me ??? I fixed for you !!!!! Why are u so bad with CocoaPods, You can build your library and share via CocoaPods, See on Firebase Or Fabric Frameworks !!!!!!!

**Comment by LeoNatan** [comment]
Listen mate!!!!! I am not here to kid anyone!!!!???!!!!

I run this project as I see fit, with quality I deem as necessary, and the features I want or be "so bad" with other features I do not want. You are free to fork this repository and do as you please under your own fork.

I will keep this open because there is a genuine issue here, but please keep a proper tone in these discussions. I have explained multiple times why I am not interested in supporting CocoaPods. Do your research by searching the issues here.

**Comment by farshadmb** [comment]
Leo. Ok I respect for your decision what ever is. I just try to fixed iOS 8 Broken for you. and fixed UITableViewController contentInsets. That all

**Comment by LeoNatan** [comment]
And I really appreciate it. But let's keep a civil tone. I will have this fix ready soon.

**Comment by farshadmb** [comment]
ok Leo . Tnq

**Comment by LeoNatan** [comment]
What OS version are you seeing this issue?

**Comment by LeoNatan** [comment]
@farshadmb If it’s not iOS 8, then please open a new issue and attach a demo project.

**Comment by farshadmb** [comment]
i will attach a screen shot as soon as possible @LeoNatan.
