### ISSUE TITLE
Question: Is the framework using Private APIs internally?

### ISSUE THREAD

**Issue by samkhawse** [LeoNatan/LNPopupController#152]
#### Description

I noticed that in the file UIViewController+LNPopupSupportPrivate.m, and I think the framework is redirecting the private APIs to custom implementation. I assume this is safe for Apple's review process and should not cause troubles while submitting the app. 

Is this assumption correct?

**Comment by LeoNatan** [comment]
The framework does some runtime trickery in order to behave properly. It should be safe for App Store submission, and people have submitted apps with the framework.

If you prefer to have a strict version of the framework, add `#define LNPopupControllerEnforceStrictClean` in the framework’s PCH file. Know, however, that this will disable a lot of crucial functionality of the framework, such as updating layout guides, transitioning the popup bar properly and so on.

**Comment by tommi** [comment]
While I appreciate all the work that @LeoNatan you have done, shouldn't the use of non-public APIs be clearly disclosed in the README.md?

**Comment by LeoNatan** [comment]
@tommi I understand what you are saying. My worry is that people will not even try to understand how this API is used and masked. I don’t know, this has been a sore point for me, as seen by the existence of `LNPopupControllerEnforceStrictClean` in there. My issue is that without the non-public API, the framework cannot achieve many of its goals. Perhaps with iOS 11 now, it will be possible, but I have not yet looked at those.
