### ISSUE TITLE
Overlapping view layout issue

### ISSUE THREAD

**Issue by kjantzer** [LeoNatan/LNPopupController#175]
I'm having issues with the view controllers in a tabbarcontroller being covered by the "now playing bar". I tried looking at #131 but haven't been able to apply that to my problem.

My pseudo code layout is:

```
let mainVC = UITabBarController

mainVC.viewControllers = [libraryVC, storeVC, settingsVC] // all 3 view controllers are UINavigationControllers

mainVC.presentPopupBar(withContentViewController: popupVC, animated: true, completion: nil)
```
My tabbar view controllers all get clipped by the popup bar:
![screen shot 2017-08-14 at 4 50 27 pm](https://user-images.githubusercontent.com/467487/29296787-6bddb242-8111-11e7-87fd-affb1162070a.png)

**What am I missing?**

> FYI: I am using a custom `LNPopupCustomBarViewController`, could that be related to the problem?

**Comment by LeoNatan** [comment]
This is on purpose.
A normal popup bar is translucent, and so, it goes above the content so that it may be seen under. This should also be the behavior of the tab bar (and navigation bar), unless you specified differently. I don't think I support (or want to support) `edgesForExtendedLayout`, where you specify that your view should shrink.

Instead, you should either set the bottom insets, in case of a scroll view, or use constraints to the bottom layout guide.

**Comment by kjantzer** [comment]
Do I need to apply the constraints on each of the tabbar view controllers?
`tabBar.viewControllers = [libraryVC, storeVC, settingsVC]`

**Comment by LeoNatan** [comment]
Each view controller has a bottom layout guide. If you set constraints against that, everything should look correctly.

**Comment by kjantzer** [comment]
Would you be able to point me in the right direction?

**Comment by LeoNatan** [comment]
You can look at the example projects to see. In the music demo, there is a scroll view. In the others, there is a constraint against the bottom layout guide.
