### ISSUE TITLE
Carthage

### ISSUE THREAD

**Issue by iDevelopper** [LeoNatan/LNPopupController#252]
Hi Leo,

This is another question, sorry!

I did not use Carthage before using your framework.

How to integrate the source file implementation (.m) to my project as I would like to set some break points in them. After adding your framework to my project, only the headers file (.h) are available.

Subsidiary question: Why this library is not available in CocoaPods too?

Regards,

Patrick

**Comment by LeoNatan** [comment]
I have a distinct CocoaPods dislike, and decided early on I do not wish to support that ecosystem. I’ve posted my reasons several times in this repo and others, and I am sure you can find those old comments.

Regarding Carthage, you can use `carthage checkout` and then integrate the project directly, rather than let Carthage build it for you. In that case, you will have the source files as well, and you can breakpoint.

**Comment by iDevelopper** [comment]
"carthage checkout" instead of "carthage update --platform iOS" in the terminal?

**Comment by LeoNatan** [comment]
I think so. I haven’t used it in a while. Personally, I use git submodules exclusively now. So much “cleaner”.

**Comment by iDevelopper** [comment]
Could you elaborate, please? I am not an expert. When creating a project witch would use your framework and have the implementation files in it, how to? You don't use anymore Carthage?

**Comment by LeoNatan** [comment]
I use git submodules.
https://git-scm.com/book/en/v2/Git-Tools-Submodules

So I add the repo I want as dependency. I then manually integrate their project into mine.

Then, if I want to advance in the dependency's version, I just change the submoulde's HEAD to point to the commit I am interested in.
