### ISSUE TITLE
Layout issue

### ISSUE THREAD

**Issue by iDevelopper** [LeoNatan/LNPopupController#256]
#### Description
When presenting popupBar, the bottom layout guide is moving correctly but the container view controller views are not. I have two buttons in a stack view. The stack view is not centered between top and bottom.

This is not relative to the stack view. If you place the buttons without a stack view, you will have the same issue.

Before presenting Popup Bar:
![2018-04-02_14-46-09](https://user-images.githubusercontent.com/1782450/38196683-b75cc0e0-3684-11e8-8e3e-62e588c7778e.png)

After presenting Popup Bar:
![2018-04-02_14-47-45](https://user-images.githubusercontent.com/1782450/38196726-de8986d0-3684-11e8-899d-1f1ace927fd1.png)

#### Steps to Reproduce
[PBLayoutPopupBarSample.zip](https://github.com/LeoNatan/LNPopupController/files/1868074/PBLayoutPopupBarSample.zip)

#### Device, OS and Xcode Versions
Xcode 9.3, iOS 10 simulator.

**Comment by LeoNatan** [comment]
What are the constraints of the stack view relative to its superview?

Just to let you know—I see you are using iOS 10 simulator—I do not plan to make major changes/fixes for iOS 10. It has become too difficult to manage both iOS 11 and iOS 10, since internally they are implemented completely differently. Please check on iOS 11, if there is a bug. I am not sure there is in this case.

**Comment by iDevelopper** [comment]
The stack view is centered horizontally and vertically relative to its superview.  I sent you my sample yesterday.

This is the same behaviour on iOS 11 and with your sample too (the Next button does not move up when the popup bar is presented.

**Comment by LeoNatan** [comment]
If you center against the superview, this is the actual expected behavior. You can test this on your own by, for example, hiding the navigation bar but showing a tab bar. It will not influence the center position (and it shouldn't). The only for this behavior is when the bars are opaque and the draw under opaque bars is disabled. In that case, the inner controller's view is actually smaller and does not reach the end of the screen. But that is not something this framework does.

**Comment by iDevelopper** [comment]
I think you should update the constraints of the content view controller (container) when you change its insets (bottom).

**Comment by LeoNatan** [comment]
This is the system behavior and I have no foothole to change it’s behavior. The superview remain the same size after presentation, so the constraints remain.

**Comment by LeoNatan** [comment]
If you center your content in the safe area center, rather than the superview center, you should achieve the desired behavior. In this case, you have set up the wrong constraints.

**Comment by iDevelopper** [comment]
Yes you are right, when I center the content to the safe area, it is OK, but the default behaviour
 in Xcode when you want to center a view is relative to its superview.

**Comment by LeoNatan** [comment]
And it’s iOS 11 only.

**Comment by iDevelopper** [comment]
Right!
