### ISSUE TITLE
LNPopupController is an amazing project. I wish there is a Swift version of it. Is there a quick way to convert it?

### ISSUE THREAD

**Issue by waelsaad** [LeoNatan/LNPopupController#301]
Hi,

LNPopupController is an amazing project even that it is 3 years old, I am just wondering if anyone or there is any intentions of re-writing this completely in swift or if there is another project that is similar in Swift

I am specifically interested in the Music Player and the popup part of it.

Thank you,

Wael

**Comment by LeoNatan** [comment]
Why would I rewrite it in Swift? What would be the benefit? What usecase are you seeing now that is not possible or less convenient to do in Swift?

**Comment by LeoNatan** [comment]
Some of those points are unrelated to the framework itself (3, 5). Others have already been asked (see #143, #211, #285), but due to time constraints, I have not been able to attack.

However, the potential of contributions alone, is not a reason enough to ask for a complete rewrite in a different language. This framework makes extensive use of Objective C runtime, which would be a pain to do in Swift, and also pointless. Swift is not a ready language yet. Closing this issue.

**Comment by LeoNatan** [comment]
But thank you for your willingness to help! I think you'll find that ObjC is not as bad as you think. 😄
