### ISSUE TITLE
Xcode 10.2

### ISSUE THREAD

**Issue by iDevelopper** [LeoNatan/LNPopupController#339]
Hi @LeoNatan ,
#### Description
We can not run your example with Xcode 10.2 because of new values for colors in storyboards. Is that intentional?
#### Steps to Reproduce
Open example project with Xcode 10.2 and select Main.storyboard.

**Comment by LeoNatan** [comment]
Yes, this was intentional. The demo project now requires Xcode 11 to build. The framework itself can be built on Xcode 10. I just couldn't find a convenient way to start supporting all the iOS 13 features without upgrading the demo project, and I didn't want to duplicate into two projects or branches. The demo project has become, over the years, my testing tool for the framework.
