### ISSUE TITLE
multiple instance of popUpContentViewController created when presenting popupContent

### ISSUE THREAD

**Issue by Frankenstein666** [LeoNatan/LNPopupController#353]
I have a setup where i am receiving an array of videoURL from REST api which are displayed in a collection view. When a cell is tapped i play the video in AVPlayer contained in the popUpContentViewController. My Problem is whenever i present a popUpContentViewController a new instance is created and viewDidLoad is called in the popUpContentViewController even if the popupPresentationState is other than hidden.
Pretty much similar to the MusicDemo example.

due to this i have multiple avPlayer instances playing multiple videos whenever popUpContentViewController is presented.

Is this an expected behaviour?
How can i present the popup for the first tap only and from next time on just update data on popupbar and popUpContentViewController.

**Comment by LeoNatan** [comment]
Hello,

The demo app is not an actual application. There are many ways you can achieve what you want. You could reuse the same controller, and just pass your playback information to the existing one that is presented, and update the popup item. You could notify the existing one to stop playing and then present a new one. And so on. Expected behavior is what you implement in your application.
