### ISSUE TITLE
Issue with popup safe area insets

### ISSUE THREAD

**Issue by ilijapuaca** [LeoNatan/LNPopupController#360]
#### Description
I'm trying to implement a custom popup view controller that looks like so:

<img width="373" alt="Screen Shot 2019-09-19 at 16 07 08" src="https://user-images.githubusercontent.com/3406718/65251604-e8431b00-daf7-11e9-9bc0-435190f4c227.png">

It does indeed look like that when it's presented initially, but once I tap it, `viewSafeAreaInsetsDidChange` gets called in my custom view controller with bottom inset value set to 0, when it had the correct value previously. The bottom inset then stays 0 the entire time, messing up the interface and making it look like so:

<img width="374" alt="Screen Shot 2019-09-19 at 16 12 28" src="https://user-images.githubusercontent.com/3406718/65251829-4cfe7580-daf8-11e9-96b5-50bed779958f.png">

I tried putting workarounds in place that somewhat mitigate the issue, but having to provide `additionalSafeAreaInsets` just to patch up the issue doesn't seem right.

I'm hoping the issue is easily reproducible. If not, I can provide relevant code.

In general, is this kind of interface supported? ie. docking to the bottom of the superview, not safe area, and adjusting the `preferredContentSize` based on whether safe area is present or not? In order to achieve this I had to set `insetsForBottomDockingView` to `.zero` and mess around with the docking view itself.

I may be doing something wrong, let me know if there's an easier way to go about this.

#### Steps to Reproduce
Present a popup bar, expand the content view controller and then close it

#### Device, OS and Xcode Versions
Simulator, iOS 12.4, Xcode 10.2

**Comment by LeoNatan** [comment]
While I would like this to be supported, I think there is a conflict between the popup bar and the insets. Since the popup bar is added to the container controller's view, and the container controller's safe area is adjusted, my guess is there is a conflict.

Since your popup bar is white, as a workaround, I would suggest creating a custom bottom docking view at the height of the window's bottom safe area inset (so as not to be in conflict with the popup's added inset) and update that when the safe area changes (due to rotation, for example). Then present the top bar as your custom popup controller.

https://github.com/LeoNatan/LNPopupController/blob/4f02ff19d4af1a8ec16e41521cc10561f6e57737/LNPopupController/LNPopupController/UIViewController%2BLNPopupSupport.h#L188
https://github.com/LeoNatan/LNPopupController/blob/4f02ff19d4af1a8ec16e41521cc10561f6e57737/LNPopupController/LNPopupController/UIViewController%2BLNPopupSupport.h#L195

**Comment by ilijapuaca** [comment]
As you can notice in the screenshot, there's a subtle gray border that's supposed to be in place (which I'll try to round for iPhone X, it's still WIP), I also want to make the background translucent, so I'd like to keep the popup view in one piece, if possible.

The workaround that I have in place right now, which sets `additionalSafeAreaInsets` whenever `viewSafeAreaInsetsDidChange` notifies me that bottom inset was set to 0 seems to work for now, as portrait is the only supported orientation right now. If/when we start supporting landscape, I'll likely have to revisit this.

Does this sound like a reasonable approach for now, or would you suggest another solution with UI details above in mind?

**Comment by LeoNatan** [comment]
What about using the window's safe area, rather than the view's, for height?

**Comment by ilijapuaca** [comment]
While that would address the issue with height, the layout would be messed up in that case (unless I'm missing something), as the content portion of my view is anchored to the safe area at the bottom.

**Comment by LeoNatan** [comment]
Yes, that's a problem. I would suggest trying to find a way not to anchor to the safe area. For example, you can keep a reference to your bottom constraint (anchored to the bottom of the view), and update its value according to the window bottom safe area inset.

It wouldn't be advisable to anchor to the safe area in either case, even if everything worked correctly, because as the popup would open, your content would shift down. That would be an unwanted behavior, I think.

**Comment by ilijapuaca** [comment]
That should work, I'll give it a try.

Thanks for the quick replies!

**Comment by LeoNatan** [comment]
BTW, any reason why you are using a custom popup bar controller? For the button shadow and border?

**Comment by ilijapuaca** [comment]
I'll also be adding a progress bar up top that looks way different compared to what's there by default, and several other things are just "a little different", so it made sense quickly getting a custom view up and running.

**Comment by LeoNatan** [comment]
Adding the project as a subproject should not be any different than adding the project if it was locally found. If it works on a clean project, then something in your current project is broken. Normally, when you link a framework with your project (be it a subproject or a precompiled framework), Xcode is able to automatically figure out the header search path, without you setting the search paths manually. From my experience, if you need to set header search paths, something has gone wrong, especially when dealing with Xcode frameworks. Sadly, this is why I so much dislike CocoaPods and its pervasive project modifications and overrides.

**Comment by SeanFromTheMatrix** [comment]
I am having a similar issue. However, the top cell in the tableView is getting pushed up underneath the navbar when I present the popUp bar. It only happens on one viewController. Any ideas, this issue did not occur until I updated to iOS 13.

**Comment by LeoNatan** [comment]
@SeanFromTheMatrix Can you please reproduce in a small project?

**Comment by SeanFromTheMatrix** [comment]
@LeoNatan sorry i did not post an update. I fixed this by changing the **bottom** constraint. Originally it was constrained to safe area, then I switched it to the super view and it worked fine.

**Comment by LeoNatan** [comment]
Thanks for the update!

I think this issue can be closed. There is not much that can be done with regards to the original issue.
