### ISSUE TITLE
IOS 13 Support.

### ISSUE THREAD

**Issue by Razikhan111** [LeoNatan/LNPopupController#367]
Hello Leo,
I am facing problem for ios 13 for present a controller  with pop up.
I am using method this method:-
self.tabBarController?.presentPopupBar.... 
It work in ios 12 and previous but didn't  work in ios 13.
My application crash due to apple UIPresentation style and your code doesn't support this.
Please help me to solve this.
I am attaching a debuging video link where a got crash.
Video Link:- https://www.dropbox.com/s/risow35dgts5779/Screen%20Recording%202019-10-23%20at%206.55.12%20PM.mov.zip?dl=0

**Comment by LeoNatan** [comment]
Hello

Looking at the video, I don't understand why you think the size of the popup bar has anything to do with the crash? The popup bar has 0 height because it's closed. On the other hand, the crash is about `UIImage`. It looks like you are using an old version of the framework. Make sure to use the latest code.
