### ISSUE TITLE
Can not find the class MarqueeLabel

### ISSUE THREAD

**Issue by dangtaikhtn** [LeoNatan/LNPopupController#376]
Hi @LeoNatan , I have installed your library by manually but in my project can not find the MarqueeLabel, the logs as below:
"Unknown class MarqueeLabel in Interface Builder file."

Can you help me how to resolve it? 
Thanks

**Comment by LeoNatan** [comment]
Hello,

I'm not sure I understand. Are you using MarqueeLabel in your storyboard? (LNPopupController does not use storyboards/nibs by itself.)
How exactly did you integrate?

**Comment by dangtaikhtn** [comment]
Hi,
- Yes, I am using MarqueeLabel in storyboard. In the example project that you already to use it.
<img width="630" alt="storyboard" src="https://user-images.githubusercontent.com/3297638/71523907-9cc1b980-28fd-11ea-9850-98943c7bb016.png">

- And I have another question: the label in mini player did auto scrolling with a long text. Can you help me to fix it?
![Simulator Screen Shot - iPhone 7 - 2019-12-27 at 23 09 58](https://user-images.githubusercontent.com/3297638/71523985-0c37a900-28fe-11ea-9c69-36dd710b7699.png)

**Comment by LeoNatan** [comment]
I see the problem. LNPopupController uses internally MarqueeLabel, but it goes out of its way to hide that, so that there is no collision if you want to use MarqueeLabel in your app. If you do want to use that, you should bring your own version of MarqueeLabel (however you wish), and use that, just like the demo project does.

Regarding scrolling, read the header file documentation.
