### ISSUE TITLE
Is is possible to use in SwiftUI?

### ISSUE THREAD

**Issue by muhasturk** [LeoNatan/LNPopupController#378]

**Comment by LeoNatan** [comment]
I’m sure it is, but I haven’t actively played around with it. 

Since the concept of controllers is foreign in SwiftUI, you’d have to create a hosting controller (`UIHostingController`), and present the popup controller on that. The popup content content controller can also be a Swift UI hosting controller.

**Comment by muhasturk** [comment]
The problem that I could not imagine is `NavigatienView` generates UINavigationController implicitly and don't know how can we subclass it and implement LNPopupController.

**Comment by LeoNatan** [comment]
You can pause an app and dump the controller hierarchy to see if it is implemented using a `UINavigationController` or not (I'm sure it is because why would they write the same code twice?).

I don't know what to advice you. I don't use SwiftUI and have little interest in it. To me, it's not a good architecture and not something I'd enjoy. The framework is heavily implemented on top of `UIViewController`, as that to me is the most elegant way to implement. I am leaving the issue open as others may join in and assist. If you figure it out, please post here, and I will update the documentation.

**Comment by iDevelopper** [comment]
I have the same interest as that of @LeoNatan . There is indeed an instance of UITabBarController or UINavigationController when we observe the hierarchy in the Debug View Hierarchy, but we do not have access to it. Did SwiftUI want to imitate HTML coding? I do not see the interest !

**Comment by LeoNatan** [comment]
I've been looking a little into the internals of SwiftUI, and perhaps an approach similar to the [SwiftUI-Introspect](https://github.com/siteline/SwiftUI-Introspect) project can be adopted, where in runtime, the view controller is discovered and then presentation can be performed on it. I don't know how stable this approach is (e.g. when SwiftUI rerenders, how often is the controller instance thrown away vs preserved)? If the implementation is stable, a SwiftUI wrapper around LNPopupController can be created.

**Comment by LeoNatan** [comment]
So, in my investigation, I created a `LNPopupView` wrapper view, where you can put your `TabView` or `NavigationView`, and it can automagically discover the `UITabBarController` or `UINavigationController` (or none, for a simple view controller presentation).

So I was thinking about a syntax of this sort:

```swift
LNPopupView {
	TabView {
		//...
	}
	.popUp(isBarPresented: $showingPopupBar, open: $popupOpen, content: {
		//Popup content
		Text("asd")
		.popupTitle("Title")
		.popupImage(Image(systemName: "star"))
		.popupBarButtonItems {
			Button("Press Me") {
				self.showingDetail.toggle()
			}
		}
	})
}
```

I still have no idea how `ModifiedContent` (view modifiers) works in SwiftUI, and not sure if it's possible to make all the presentations and opening and closing and dismissing stuff work with the state system of SwiftUI. Actively thinking about this.

**Comment by LeoNatan** [comment]
https://github.com/LeoNatan/LNPopupUI 🎉

Enjoy!
