### ISSUE TITLE
Swift Package Manager question

### ISSUE THREAD

**Issue by iDevelopper** [LeoNatan/LNPopupController#410]
#### Description
Hello,
This is a question:
How to edit the framework code (and possibly send a pull request) when using SPM in a new project?
I didn't find much on SO.
Maybe you can get me started.
Thanks.

**Comment by LeoNatan** [comment]
No really good way that I found. See what I do in LNPopupUI:

https://github.com/LeoNatan/LNPopupUI/blob/94e5a1ff1de69e07ae6fb740e7d130f1773f1474/Package.swift#L23

I just uncomment this out when developing, so it's a local package instead of a GitHub one. Then Xcode will allow you to edit the files.

**Comment by iDevelopper** [comment]
Thanks for reply. I'll take a look.
Cheers,

**Comment by LeoNatan** [comment]
Cheers!
