### ISSUE TITLE
Undefined symbols for architecture armv7

### ISSUE THREAD

**Issue by FoksWang** [LeoNatan/LNPopupController#412]
I have been using this library for several months, and it was working fine. In the recent upgrade, however, the library occurred a problem of the compilation and packaging failed. The previous version v2.8.5 worked was normal. Please help to take a look at what happens in the new versions.

#### Description
Linking:
⚠️  ld: ignoring file /Users/runner/work/1/s/Carthage/Build/iOS/LNPopupController.framework/LNPopupController, missing required architecture armv7 in file /Users/runner/work/1/s/Carthage/Build/iOS/LNPopupController.framework/LNPopupController (2 slices)
❌  Undefined symbols for architecture armv7
> Symbol: _OBJC_CLASS_$_LNPopupCustomBarViewController
❌  ld: symbol(s) not found for architecture armv7
❌  clang: error: linker command failed with exit code 1 (use -v to see invocation)
** BUILD FAILED **

#### Device, OS and Xcode Versions
Xcode 11.6
LNPopupController: v2.10.8

**Comment by LeoNatan** [comment]
Hmm, I thought it was a bug, but I think it's by design. Versions 2.9.0 and above require iOS 11 and above, which is 64-bit only. Please see https://github.com/LeoNatan/LNPopupController/issues/335
I suggest you either drop iOS 10 and below, or if you must keep support, use version 2.8.5. Just be aware that there have been many fixes since 2.8.5 (especially for iOS 14).

**Comment by LeoNatan** [comment]
If your app is iOS11+, then you might have misconfiguration in your project.

**Comment by FoksWang** [comment]
Wow, thank you very much for your answer👍 You are right, the problem was solved by setting the target version to iOS 11 in Xcode. Thanks again!!

**Comment by LeoNatan** [comment]
Great
