### ISSUE TITLE
How to add google analytics to LNPopupController

### ISSUE THREAD

**Issue by nhatduong** [LeoNatan/LNPopupController#433]
Hello,
I added google analytics code to my code, but it not working.
What needs to make the google analytics code work.

Thank you.

**Comment by LeoNatan** [comment]
I have no idea. Why ask me how to integrate analytics in your app?

**Comment by iDevelopper** [comment]
https://firebase.google.com/docs/ios/setup?authuser=0

**Comment by nhatduong** [comment]
because, I added google analytics code but it doesn't work on LNPopupController, other screens google analytics still works.

**Comment by iDevelopper** [comment]
LNPopupController is not a view controller. What is not working?

**Comment by LeoNatan** [comment]
I guess the problem is that the Google Analytics doesn't report the content controller as being open?

I have no idea how Google Analytics figures that out. If they only look at pushed and presented view controllers, then they won't catch controllers shown by this framework. Instead, you can manually notify the Analytics SDK when your screen is opened and closed.

**Comment by iDevelopper** [comment]
Example:
```
    override func viewDidAppear(_ animated: Bool) {
        super.viewDidAppear(animated)
        Analytics.logEvent("viewDidAppear", parameters: [AnalyticsParameterScreenName: "PlayViewController", AnalyticsParameterScreenClass: classForCoder.description()])
    }
```

**Comment by nhatduong** [comment]
@iDevelopper thank you very much.
