### ISSUE TITLE
Set to pull down a longer distance to close Popup？

### ISSUE THREAD

**Issue by CivelXu** [LeoNatan/LNPopupController#473]
Now when you go to pull down a little bit, popup put it away。 I want to set a longer distance to reduce the agility of the drop-down popoup.

**Comment by LeoNatan** [comment]
Hello,
Use the .drag interaction style. 
https://github.com/LeoNatan/LNPopupController/blob/f1d3b02d1aaa5b7990beceb3691b8aea05e64846/LNPopupController/LNPopupController/UIViewController%2BLNPopupSupport.h#L35

**Comment by LeoNatan** [comment]
Depending on how difficult this turns out to be (I haven't touched that part of the code in years), I might add a delegate method or a property to control this.

**Comment by LeoNatan** [comment]
Implemented. Use `popupInteractionStyle = .customizedSnap(percent: 0.6)` to control the percent of drag before the popup is closed.

**Comment by CivelXu** [comment]
I use the .drag interaction style in my app. But the gesture is very easy to touch by mistake to close the popup.I can show you a video.

https://user-images.githubusercontent.com/19768199/128636124-aa5ff9ea-5eff-4097-85b9-48571141fcf2.mov

**Comment by LeoNatan** [comment]
That was the behavior of the popup in Apple's apps, before they switched to the snap behavior. I got it to behave very similarly. Basically, if you stop your gesture at the direction of dismiss, it dismisses. You can look at the internal logic for that. I haven't touched it in years because it was very close to Apple's behavior.
