### ISSUE TITLE
Describe what LNPopupControllerEnforceStrictClean means

### ISSUE THREAD

**Issue by akac** [LeoNatan/LNPopupController#54]

**Comment by LeoNatan** [comment]
Have you taken a look at the code? 😉

**Comment by akac** [comment]
Yes…but instead of setting that #define to see what happens when all the good stuff is removed, it would be nice to have a list of "this won't work".

**Comment by LeoNatan** [comment]
Good point. I have not tested, not attempted to fix issues that might arise from removing. 

Major stuff to go away:
Layout guide management
Status bar management
Small fixes done in "the good stuff" to counter or sidestep Apple issues

I don't think this should be "exposed" in the official documentation / readme. It's gray area and safe. It's there as an Easter egg, a private API of the framework, if you will, for the curious and those willing to inspect properly. Maybe a comment next to the #define.

**Comment by akac** [comment]
My problem is that I'm testing this framework in a VC which includes a table view - but the table view isn't getting its content offset so the bar is over the table view over its last row. I'm trying to identify how this all works, so I can properly fix it…but its quite obfuscated so its hard to know.

**Comment by LeoNatan** [comment]
It's obfuscated because it has to be.

To fix, you need to update the table view insets after presenting the popup bar.

This is true for Apple frameworks as well. Insets of scrollviews are only modified before presentation of the view, then they are not modified by UIKit. So if something triggers a layout guide update after presentation, it is up to the developer to update the content insets. 

Best solution is to implement `viewDidLayoutSubviews` and set the content insets there to be equal to the top and bottom layout guides. See the music album demo, where I did just that.

**Comment by akac** [comment]
Aha, ok. I should've know that. Thanks.
