### ISSUE TITLE
Is it possible to make it globally accessible?

### ISSUE THREAD

**Issue by Jamal1337** [LeoNatan/LNPopupController#62]
Hey, first of all thank you very much for providing this sweet piece of code, it is very great and helpful!

I just have a question, as I am trying to use this like a global View at the bottom of each ViewController, I was wondering if it is possible to have that bottom bar fixed across all ViewControllers like a ContainerView with having everywhere the same content? Right now I add the popupContentController to each ViewController individually and have to store the currently playing Song information globally.

Thanks!

**Comment by LeoNatan** [comment]
How are open are you to changes in your design? I have some tricks.

What is your app's controller hierarchy? A navigation controller, where other controllers are pushed/presented?

**Comment by Jamal1337** [comment]
I have a sidebar menu with serveral navigation points. Each ViewController is embedded in its own NavigationController. Sometimes there are TableViews where it is possible to go a little bit deeper.

My initial Controller is the top one in the image where i add the popupContentController to its navigationController. But if I switch, I have to initialize it again

My Storyboard looks like this:
![screen shot 2016-04-28 at 11 31 41](https://cloud.githubusercontent.com/assets/6834031/14881597/f367a8a0-0d34-11e6-999e-77039debae9e.png)

**Comment by LeoNatan** [comment]
Here is the simplest solution I can think of, with one caveat which you will have to handle across the project.

Create a second window (`UIWindow`), with a clear view controller. Make sure to have a strong reference to that window object. Present the popup bar on that. Now you have the a globally available popup bar on top of all other view hierarchy.

The only issue now is, you have to set a bottom content inset manually to all your scrollviews which overlap. That's not that bad already. However, if you have a navigation bar showing a toolbar, this will not work, as you cannot move the toolbar normally.

Another solution to this is, to change the root controller of the scene (which is the root controller of the normal application window, the one below our new one) to a container controller and put the content view controller as your normal navigation controller (the previous root controller of the scene). Add a constraint to the container view, raising it a little on the bottom (to the height of the popup bar). Now all your normal hierarchy is container inside this area above the closed popup bar. This solution will have some trouble with the default modal presentations, because they are not presented inside the container view, so they will have the issues discussed in previous proposed solution.

When opening the popup bar, the controller will open in the second window and will not interfere with what you have on your normal hierarchy. Pair this with some translucent background view for your popup content controller, and you'll have a very cool effect.

**Comment by Jamal1337** [comment]
Thanks!
I'm just trying to add a second window, but have nerver done this. I try to add one programmatically in the  didFinishLaunchingWithOptions of the AppDelegate, is that correct? And then I try to append the popup bar to this window.

Another thing that comes to my mind is, doesn't the second window prevent the user from navigating through the app if the second window overlays the main window?

**Comment by LeoNatan** [comment]
Make a strong property for the second window. Then,

```
self.popupWindow = [[UIWindow alloc] initWithFrame:[UIScree mainScreen].bounds];
self.popupWindow.rootViewController = [UIViewController new];
self.popupWindow.rootViewController.view.backbroundColor = [[UIColor greenColor] colorWithAlphaComponent:0]; //The reason I do it like this is to work around an iOS bug
self.popupWindow.rootViewController.view.userInteractionEnabled = NO; //This will disable touches on the view itself, allowing the touches to pass to the window below.
```

Then, present the popup bar on `self.popupWindow.rootViewController`.

**Comment by Jamal1337** [comment]
Okay I got it appearing, but I either cannot click on anything or just click on the basic UIWindow but not on the Player within the second UIWindow.

here is my (your) code:

`secWindow = UIWindow(frame: UIScreen.mainScreen().bounds)
        secWindow?.rootViewController = UIViewController()
        secWindow?.windowLevel = UIWindowLevelAlert
        secWindow?.rootViewController?.view.backgroundColor = UIColor.greenColor().colorWithAlphaComponent(0)
        secWindow?.rootViewController?.view.userInteractionEnabled = false
        secWindow?.hidden = false`

with this code I cannot interact with anything on the screen.
If i add this line, I can interact with the base UIWindow but not with the Player:
`secWindow?.userInteractionEnabled = false`

and if I set that value to "true" I can interact with the Player UIWindow but not anymore with the base UIWindow

**Comment by LeoNatan** [comment]
Hmm, will take a look how to solve when I am near my Mac.

**Comment by Jamal1337** [comment]
Okay I will continue trying to get it work, but thanks very much for your fast responses!

**Comment by LeoNatan** [comment]
OK, so I ended up having to create this small piece of code.

Objective C:
```objc
@interface LNOnlyPopupTouchesWindow : UIWindow @end
@implementation LNOnlyPopupTouchesWindow

- (UIView *)hitTest:(CGPoint)point withEvent:(UIEvent *)event
{
	UIView* test = [super hitTest:point withEvent:event];
	
	return test == self.rootViewController.view ? nil : test;
}

@end
```
Swift:
```swift
@objc(LNOnlyPopupTouchesWindow)
class OnlyPopupTouchesWindow : UIWindow {
	override func hitTest(point: CGPoint, withEvent event: UIEvent?) -> UIView? {
		let test = super.hitTest(point, withEvent: event)
		
		return test == rootViewController?.view ? nil : test
	}
}
```

What it does is only let touches to the popup controller and its subviews be captured by the window, otherwise let the system to pass them elsewhere (the other window). Then make sure to have your popup window be of this type.

**Comment by LeoNatan** [comment]
@Jamal1337 Did it work?

**Comment by Jamal1337** [comment]
Yes thanks a lot! I already got it working before you answered, it was nearly the same solution but a bit more complex, so I decided to adapt yours which worked absolutely flawless. Thanks a lot again for your fast help!
