### ISSUE TITLE
Hide close button?

### ISSUE THREAD

**Issue by Urkman** [LeoNatan/LNPopupController#72]
How can I hide the close button?

I tried it with:
popupContentController.popupContentView.popupCloseButton?.hidden = true

But this is not working :(

**Comment by ClapCharts** [comment]
I've used the following with swift :
`LNPopupCloseButton.appearance().hidden = true`

**Comment by LeoNatan** [comment]
Make sure to call this on the view controller you presented the popup on, not the content controller.

**Comment by colinmorelli** [comment]
I had the same issue as @Urkman when I used the code posted int he original question and didn't want to use UIAppearance to remove it. So, for anyone else who may be struggling with this problem, the solution is simple:

`self.popupContentView.popupCloseButton?.hidden = true` 

In the view controller that presented the popup. Note the lack of the additional `popupContentViewController` in the original question. Doing what is posted in the original question actually works (causes no errors) but accesses a different instance of the popup view than the one actually presented.

FWIW @LeoNatan - my reason for wanting to remove the close button is because `UIVIsualEffectView` seems to be quite the performance bottleneck on an iPhone 5 when it's over a UITableView containing images with masks (that are offscreen-rendered). It worked fine over every other view in my application but not on this one view, where opening and closing the popup controller would cap at ~35fps (compared to 60 on other views that didn't have a bunch of images in a table view). Personally I don't need the blur effect so I'm fine removing the button but is there another way to disable it while keeping the button?

**Comment by LeoNatan** [comment]
@colinmorelli Are you that worries about iPhone 5? How many of those (along with 4S) are you seeing among your users? Another option is to expose the effects view of the button so you can hide/disable specifically that, but I don't like that option.

**Comment by colinmorelli** [comment]
Fair point - it may not be worth doing anything about. The reason I originally started looking into it is because I was testing on an older iPhone 5 (just for the smaller screen size), and was particularly curious about how fast the performance difference was when opening the popup on two different VCs of the same app. So, it's not so much that I was worried about the iPhone 5 as it was that the iPhone 5 simply drew my attention to what I thought was an interesting problem.

That said, iPhone 5 or otherwise, I think exposing the ability for people to disable the default visual effect view would be useful anyway. It would seem that for most use cases in which your view controller has an opaque background color, you probably don't want the blurred circle sitting on top of it. But again, I would understand your decision to not want to support that.

**Comment by LeoNatan** [comment]
I disagree about the effect; the button shines the background color. I am reluctant to make a change on this. 😄
You can always add a custom button to your UI, instead of the framework provided one.
