### ISSUE TITLE
Customizable Close button

### ISSUE THREAD

**Issue by Kastet** [LeoNatan/LNPopupController#9]
Need API to customise the close button. At least to be able to hide the default one.

**Comment by LeoNatan** [comment]
Will implement close button customization soon. I am thinking of having the API in the `LNPopupItem` class.

**Comment by LeoNatan** [comment]
You can now customize or hide the close button.

**Comment by Kastet** [comment]
thanks!

**Comment by RajChanchal** [comment]
@LeoNatan But it doesn't hide. tried this:
self.popupContentView.popupCloseButton?.isHidden = true  in the content view's viewDidLoad, `viewWillAppear `and `viewDidLayoutSubviews`

Tried doing the same before calling:
`self.tabBarController?.presentPopupBar(withContentViewController: player, animated: true, completion:nil)`
Note: `player` is the content view controller

The back button appears very bad actually.
![simulator screen shot 11-nov-2016 12 15 51 am](https://cloud.githubusercontent.com/assets/7058465/20192660/408e1c36-a7a4-11e6-99f5-b75c7037aeaa.png)

**Comment by RajChanchal** [comment]
I had included this lib by cocoapod and it didn't put in the image assets I think. Dragging the source files with xproj file and image asset, did show the close button image fine at last. Please do solve the problem with cocoapods too.

**Comment by LeoNatan** [comment]
Do not use CocoaPods. It is **not supported**. You are probably using a fork, which is most likely old. Please use the recommended way, Carthage (or git submodule, etc.). 

The reason the button is not hidden is because you are presenting the popup on the tab bar, but hide the button for `self`. Hide it for the tab bar.

Again, do not use CocoaPods versions. Use the official repo. If you must, fork it yourself and maintain it, however I do not recommend forking just for CocoaPods.
