### ISSUE TITLE
How To Customize Popupbar using IB?

### ISSUE THREAD

**Issue by glennposadas** [LeoNatan/LNPopupController#94]
Hello, I've been trying to make a custom view as the popupbar of my app. Any tutorials or wiki for this? Thanks!

**Comment by LeoNatan** [comment]
You cannot customize it using IB. You need to use code, as described in the README.

**Comment by glennposadas** [comment]
Hi, that was fast. Thanks so much for the reply. If I do have a question, is it fine if I open a new ticket or just reply to this thread or should I email you? I actually got another question, any idea how to convert this into Swift?
I used to code in objective-c and now in swift, but I still don’t know how to convert this one:

[[LNPopupBar appearanceWhenContainedInInstancesOfClasses:@[[UINavigationController class]]] setTintColor:[UIColor yellowColor]];

**Comment by LeoNatan** [comment]
This is very basic stuff.

http://stackoverflow.com/questions/24136874/appearancewhencontainedin-in-swift

**Comment by glennposadas** [comment]
alright, thanks a lot again! Yea basic indeed, I forgot that kind of syntax.
G

**Comment by glennposadas** [comment]
Hi Leo, sorry for the continuous annoying questions, but how can I setup a new height for my popupbar? I think if I can change the popupbar’s height, then this will be my last question. I’ll try to search your LNPopupController on Stackoverflow to see if someone asked the same question. Thanks!

G

**Comment by LeoNatan** [comment]
Sorry, this is not supported. The popup bar height is constant.

**Comment by glennposadas** [comment]
Hi Leo,

I actually made a way, I hope you don’t mind if I modified the constant height of the popup bar from 40.0 to the height I need: 64.0.

Anyway, is it possible to make this PopupController to be ALWAYS ON TOP OF EVERY SCREENS in my app? [http://stackoverflow.com/questions/38811311/how-to-always-show-a-viewcontroller-even-when-navigating-screens-in-ios <http://stackoverflow.com/questions/38811311/how-to-always-show-a-viewcontroller-even-when-navigating-screens-in-ios>]

Thanks!

Glenn

**Comment by wytemusic** [comment]
@glennposadas have you ported it to Swift? I'm currently trying to to the same (porting it to Swift) and I am somewhat stuck and don't know where to begin.

**Comment by glennposadas** [comment]
@wytemusic Everything written in Objective-C can be used in your Swift project easily by using `Bridging Header`. Thus you should be able to use this library without re-writing anything. Search for that and you shall be enlightened. It's pretty easy.

Also, author says: 

> Check the demo project for many common use cases of the framework in various scenarios. It contains examples in Swift and Objective C.

**Comment by LeoNatan** [comment]
BTW, @glennposadas, it is now possible to provide custom bars with custom heights. (Not sure if you are up to date with the updates of the framework.)

**Comment by wytemusic** [comment]
@LeoNatan My project is always crashing because of an unrecognised selector being sent to an instance. May I send you my project (it is extremely small and only for testing purposes of the controller intended) for you to review it? A second pair of eyes is always useful. Thank you in advance!

**Comment by wytemusic** [comment]
@glennposadas what is the procedure? How should my bridging header look like? I'm fairly new into programming for iOS and have never really worked with obj c code. Thus I would really appreciate your help! :)

**Comment by LeoNatan** [comment]
Please open a dedicated issue, and paste the relevant portions of your code that is crashing.

**Comment by LeoNatan** [comment]
But please note that this is not a support forum. There are many, many resources to help you set up a bridging header, including guides by Apple. Please read those.

**Comment by wytemusic** [comment]
@LeoNatan the code is not crashing because of a bug. I have just trouble setting it up. 
Regarding your example project: I essentially want to copy the music player into another project. I tried to copy the swift files regarding the music player and the storyboard (Music.storyboard) content and importing the framework via Carthage. That doesn't work properly. It doesn't crash but for example clicking on the bar doesn't open it and the title, subtitle and left & right BarButtonItems are completely misaligned. 
There seem to be some other functions in "FirstViewController.m". E.g: "_presentBar:(id)sender", "_dismissBar:(id)sender", "previewingViewControllerForPopupBar:(LNPopupBar*)popupBar". Do I need to port those too? I'm really sorry for the inconvenience.

**Comment by LeoNatan** [comment]
`previewingViewControllerForPopupBar:` (and the Swift equivalent) is a delegate method for 3D touch support (force–press on the bar on devices that support that). It is not required.

`_presentBar:` and `_dismissBar:` are internal example logic that present and dismiss the popup. Instead of copying them, try to understand the logic there (the music app is very simple), and try to implement it on your own.

**Comment by wytemusic** [comment]
Thank you for your help!
