### ISSUE TITLE
I'm getting 'Please adopt the iOS 9 API' when running the code

### ISSUE THREAD

**Issue by Matiaz** [LeoNatan/LNPopupController#98]
`Sending -viewForBaselineLayout to a member of __MarqueeLabel in lieu of -viewForLastBaselineLayout. Please adopt the iOS 9 API.`

Basically I'm using the latest version of the code and running the code on iOS9, do you know if this is a bug or how to solve that ? Thanks

**Comment by LeoNatan** [comment]
Hmm, I am not familiar with the issue. I see that `-viewForBaselineLayout` is deprecated in SDK9. Did you modify the target of the framework to be SDK 9 and above? I'll see what I can do when I have time.

**Comment by Matiaz** [comment]
No I haven't, I'm gonna continue investigating that... I'm also having a hard time trying to solve a problem with the content view, the LNPopupBar sits on top of my content, I don't know how to update the content view so it doesn't get hidden behind the bar... 

I'm trying to imitate what you did here with the "correct bottom layout guide"

<img width="672" alt="screen shot 2016-08-19 at 5 44 44 pm" src="https://cloud.githubusercontent.com/assets/757195/17827073/ae663dda-6634-11e6-87ee-7b5431756926.png">

**Comment by LeoNatan** [comment]
Set up a constraint between the bottom of your view and the bottom layout guide of the controller. If you are not using constraints, you should update your view hierarchy in `-viewDidLayoutSubviews` in the controller, taking into account the controller's `bottomLayoutGuide`. This is true for iOS in general; my framework just makes sure to update the layout guide correctly so that layout is correct.

**Comment by LeoNatan** [comment]
@Matiaz Added a proposed fix in 2_0 branch. Please test.
