### ISSUE TITLE
Opening pan gesture recogniser doesn't function correctly.

### ISSUE THREAD

**Issue by technicalflaw** [LeoNatan/LNPopupController#99]
I'm having trouble making the initial pan gesture recogniser function. In the example project it is possible to drag the popup bar to open it, but with the current version the pan gesture is handled as a tap would be.

Upon further investigation it seems the version used in the example is different (presumably older). As far as I can see the issue is in `LNPopupController::_transitionToState`, where the pan gesture recogniser is swapped from the popup and added to the view of the content view controller. In the latest version the swap happens immediately in the `closed` to `transitioning` state change (line 312), causing the pan gesture that caused the popup to enter the transition state to be cancelled,  whereas in the old version in the example it happens in the animation's completion block (line 336). Moving line 312-313 to 340 seems to fix it, although I don't know if there are any side effects.

Thanks for an excellent, well written project! As a side note, please use mp4 instead of gif for the animations, as they're a bit massive :)

**Comment by LeoNatan** [comment]
Thanks for your kind works and bug report.

Errm, must have gone wrong in one of my last commits. I will take a look. I also started work on #91 in a different branch, but may take a look to fix this before continuing there.

**Comment by AnasMostefaoui** [comment]
Hello, 

I was facing same issue, I'm using the library with Swift 3 and iOS 9.0 with xCode 8.
The pan gesture was not working at all, after some quick investigation, I found that the issue was in **LNPopupController.m** file , on this method : 


`- (void)_transitionToState:(LNPopupPresentationState)state animated:(BOOL)animated completion:(void(^)())completion userOriginatedTransition:(BOOL)userOriginatedTransition
`

Exactly in this line : 
`[_popupBar removeGestureRecognizer:self.popupContentView.popupInteractionGestureRecognizer];`

Commenting this line made the pan gesture work again.

I think it worth notice that I'm using an older version(1.4.1) of the library, and was working perfectly in iOS >= 7.0 , Swift 2.2 and xCode 7.x.

hope this can help for a better solving of the issue.

**Comment by LeoNatan** [comment]
@AnasMostefaoui @technicalflaw Can you guys test branch 2.0 to see if it reproduces there?

**Comment by technicalflaw** [comment]
I'm not at Xcode so I can't check branch 2_0, but the [commit](https://github.com/LeoNatan/LNPopupController/commit/39fd875ebc6fabd52c0a95c4b06f027b5201153c) for Fix #90 on Aug 6 definitely worked for me.

**Comment by AnasMostefaoui** [comment]
I just try the 2.0 version, and the issue is fixed, thanks a lot.

**Comment by LeoNatan** [comment]
Interesting. Well, branch 2_0 is not stable yet, but I should take a look what changed and cherry pick it. I have been very busy lately, but will do it eventually.

**Comment by AnasMostefaoui** [comment]
When I tried to use it on a swift 3.0 project targeting iOS >= 9.0, i got the same issue than this one #105 but in my case its on presentPopupBar method, I will try to find what's happening and will let you know

**Comment by LeoNatan** [comment]
Great, thank you! @AnasMostefaoui

**Comment by AnasMostefaoui** [comment]
@LeoNatan  welcom, you can check my workaround for #105 
Thank you for this great library 👍
